[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONWebTokens = "9b8beb19-0777-58c6-920b-28f749fee4d3"
JWTs = "d850fbd6-035d-5a70-a269-1ca2e636ac6c"
ResultTypes = "08a2b407-ddc3-586a-afd6-c784ad1fffe2"
Superfacility = "f7a38f07-e5d6-4eec-ba19-7d8f01225f45"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
